# Generated by Django 6.1 on 2026-08-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationstate',
            name='state',
            field=models.CharField(choices=[('awaiting_course', 'Awaiting course'), ('awaiting_section', 'Awaiting section'), ('awaiting_confirmation', 'Awaiting confirmation'), ('awaiting_removal', 'Awaiting removal')], default='awaiting_course', max_length=32),
        ),
    ]
