# Generated by Django 6.1 on 2026-08-17 06:30

import core.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Must run before CourseSession's GIN trigram index, below.
        TrigramExtension(),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_num', core.fields.EncryptedPhoneField(max_length=64, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.CharField(max_length=5)),
                ('code', models.CharField(max_length=9)),
                ('section', models.CharField(max_length=3)),
                ('sem_id', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['code', 'title'], name='coursesession_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops'])],
                'constraints': [models.UniqueConstraint(fields=('crn', 'sem_id'), name='unique_crn_sem'), models.UniqueConstraint(fields=('code', 'section', 'sem_id'), name='unique_code_section_sem')],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('account_created', 'Account created'), ('watch_created', 'Watch created'), ('watch_removed', 'Watch removed'), ('sms_received', 'SMS received'), ('sms_sent', 'SMS sent'), ('seat_found', 'Seat found'), ('poll_cycle', 'Poll cycle'), ('error', 'Error')], max_length=32)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coursesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
