# Generated by Django 5.2.4 on 2025-07-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('crn', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('code', models.CharField(verbose_name=9)),
                ('section', models.CharField(verbose_name=3)),
                ('sem_id', models.CharField(verbose_name=6)),
            ],
        ),
    ]
