# Generated by Django 6.1 on 2026-08-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
