# Generated by Django 6.1 on 2026-08-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_eventlog_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='code',
            field=models.CharField(max_length=64),
        ),
    ]
