# Generated by Django 6.1 on 2026-09-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_split_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_created_watch',
            field=models.BooleanField(default=False),
        ),
    ]
