# Generated by Django 6.1 on 2026-09-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventlog_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('account_created', 'Account created'), ('watch_created', 'Watch created'), ('watch_removed', 'Watch removed'), ('sms_received', 'SMS received'), ('sms_sent', 'SMS sent'), ('seat_found', 'Seat found'), ('error', 'Error')], max_length=32),
        ),
    ]
