# Generated by Django 5.2.4 on 2025-08-28 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('seat_signal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatsignal',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_signals', to='core.coursesession'),
        ),
        migrations.AddConstraint(
            model_name='seatsignal',
            constraint=models.UniqueConstraint(fields=('user', 'session'), name='unique_user_session_signal'),
        ),
    ]
