# Generated by Django 6.1 on 2026-08-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_conversationstate_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationstate',
            name='pending_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
