# Generated by Django 6.1 on 2026-09-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat_signal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('last_seen', models.DateTimeField()),
            ],
        ),
    ]
